enum RegionFilter {
  all,
  europe,
  asia,
  southAmerica,
  centralAmerica,
  northAmerica,
}

const Map<String, Map<RegionFilter, String>> regionLabelsByLang = {
  'en': {
    RegionFilter.all: 'All regions',
    RegionFilter.europe: 'Europe',
    RegionFilter.asia: 'Asia',
    RegionFilter.southAmerica: 'South America',
    RegionFilter.centralAmerica: 'Central America',
    RegionFilter.northAmerica: 'North America',
  },
  'es': {
    RegionFilter.all: 'Todas las regiones',
    RegionFilter.europe: 'Europa',
    RegionFilter.asia: 'Asia',
    RegionFilter.southAmerica: 'America del Sur',
    RegionFilter.centralAmerica: 'America Central',
    RegionFilter.northAmerica: 'America del Norte',
  },
  'fr': {
    RegionFilter.all: 'Toutes les regions',
    RegionFilter.europe: 'Europe',
    RegionFilter.asia: 'Asie',
    RegionFilter.southAmerica: 'Amerique du Sud',
    RegionFilter.centralAmerica: 'Amerique centrale',
    RegionFilter.northAmerica: 'Amerique du Nord',
  },
  'de': {
    RegionFilter.all: 'Alle Regionen',
    RegionFilter.europe: 'Europa',
    RegionFilter.asia: 'Asien',
    RegionFilter.southAmerica: 'Sudamerika',
    RegionFilter.centralAmerica: 'Mittelamerika',
    RegionFilter.northAmerica: 'Nordamerika',
  },
  'it': {
    RegionFilter.all: 'Tutte le regioni',
    RegionFilter.europe: 'Europa',
    RegionFilter.asia: 'Asia',
    RegionFilter.southAmerica: 'America del Sud',
    RegionFilter.centralAmerica: 'America Centrale',
    RegionFilter.northAmerica: 'America del Nord',
  },
  'pt': {
    RegionFilter.all: 'Todas as regioes',
    RegionFilter.europe: 'Europa',
    RegionFilter.asia: 'Asia',
    RegionFilter.southAmerica: 'America do Sul',
    RegionFilter.centralAmerica: 'America Central',
    RegionFilter.northAmerica: 'America do Norte',
  },
  'ja': {
    RegionFilter.all: 'すべての地域',
    RegionFilter.europe: 'ヨーロッパ',
    RegionFilter.asia: 'アジア',
    RegionFilter.southAmerica: '南アメリカ',
    RegionFilter.centralAmerica: '中央アメリカ',
    RegionFilter.northAmerica: '北アメリカ',
  },
  'ko': {
    RegionFilter.all: '전체 지역',
    RegionFilter.europe: '유럽',
    RegionFilter.asia: '아시아',
    RegionFilter.southAmerica: '남아메리카',
    RegionFilter.centralAmerica: '중앙아메리카',
    RegionFilter.northAmerica: '북아메리카',
  },
  'ar': {
    RegionFilter.all: 'كل المناطق',
    RegionFilter.europe: 'أوروبا',
    RegionFilter.asia: 'آسيا',
    RegionFilter.southAmerica: 'أمريكا الجنوبية',
    RegionFilter.centralAmerica: 'أمريكا الوسطى',
    RegionFilter.northAmerica: 'أمريكا الشمالية',
  },
};

const Set<String> _europeIsoCodes = {
  'AD',
  'AL',
  'AT',
  'AX',
  'BA',
  'BE',
  'BG',
  'BY',
  'CH',
  'CY',
  'CZ',
  'DE',
  'DK',
  'EE',
  'ES',
  'FI',
  'FO',
  'FR',
  'GB',
  'GG',
  'GI',
  'GR',
  'HR',
  'HU',
  'IE',
  'IM',
  'IS',
  'IT',
  'JE',
  'LI',
  'LT',
  'LU',
  'LV',
  'MC',
  'MD',
  'ME',
  'MK',
  'MT',
  'NL',
  'NO',
  'PL',
  'PT',
  'RO',
  'RS',
  'RU',
  'SE',
  'SI',
  'SJ',
  'SK',
  'SM',
  'UA',
  'VA',
  'XK',
};

const Set<String> _asiaIsoCodes = {
  'AE',
  'AF',
  'AM',
  'AZ',
  'BD',
  'BH',
  'BN',
  'BT',
  'CN',
  'GE',
  'HK',
  'ID',
  'IL',
  'IN',
  'IQ',
  'IR',
  'JO',
  'JP',
  'KG',
  'KH',
  'KP',
  'KR',
  'KW',
  'KZ',
  'LA',
  'LB',
  'LK',
  'MM',
  'MN',
  'MO',
  'MV',
  'MY',
  'NP',
  'OM',
  'PH',
  'PK',
  'PS',
  'QA',
  'SA',
  'SG',
  'SY',
  'TH',
  'TJ',
  'TL',
  'TM',
  'TR',
  'TW',
  'UZ',
  'VN',
  'YE',
};

const Set<String> _southAmericaIsoCodes = {
  'AR',
  'BO',
  'BR',
  'CL',
  'CO',
  'EC',
  'FK',
  'GF',
  'GY',
  'PE',
  'PY',
  'SR',
  'UY',
  'VE',
};

const Set<String> _centralAmericaIsoCodes = {
  'BZ',
  'CR',
  'GT',
  'HN',
  'MX',
  'NI',
  'PA',
  'SV',
};

const Set<String> _northAmericaIsoCodes = {
  'AG',
  'AI',
  'AW',
  'BB',
  'BL',
  'BM',
  'BQ',
  'BS',
  'CA',
  'CU',
  'CW',
  'DM',
  'DO',
  'GD',
  'GL',
  'GP',
  'HT',
  'JM',
  'KN',
  'KY',
  'LC',
  'MF',
  'MQ',
  'MS',
  'PM',
  'PR',
  'SX',
  'TC',
  'TT',
  'US',
  'VC',
  'VG',
  'VI',
};

const Map<RegionFilter, Set<String>> regionIsoMap = {
  RegionFilter.europe: _europeIsoCodes,
  RegionFilter.asia: _asiaIsoCodes,
  RegionFilter.southAmerica: _southAmericaIsoCodes,
  RegionFilter.centralAmerica: _centralAmericaIsoCodes,
  RegionFilter.northAmerica: _northAmericaIsoCodes,
};
