name: cellphone_validator
description: "A widget and helper for validation internation phone numbers"
version: 1.0.5
homepage: https://github.com/Decksplayer/phonevalidator
repository: https://github.com/Decksplayer/phonevalidator

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

topics:
  - phone
  - validation
  - widget
  - form
  - international


